# Generated by Django 4.0.6 on 2022-09-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBlogApp', '0009_rename_image_post_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-published']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AddField(
            model_name='post',
            name='multimedia',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
