# Generated by Django 4.0.6 on 2022-09-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBlogApp', '0010_alter_comment_options_remove_post_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='multimedia',
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
