# Generated by Django 4.0.6 on 2022-09-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBlogApp', '0011_remove_post_multimedia_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
