# Generated by Django 4.0.6 on 2022-09-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBlogApp', '0014_alter_post_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['published']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='post',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
