# Generated by Django 4.0.6 on 2022-10-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBlogApp', '0019_profile_followers_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test_field',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
