# Generated by Django 4.0.6 on 2023-03-05 20:59

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBlogApp', '0023_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=pathlib.PureWindowsPath('C:/Users/zubok/DjangoBlogEnv/Scripts/DjangoBlogProject/static/images')),
        ),
    ]
