# Generated by Django 4.0.6 on 2023-03-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBlogApp', '0026_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='biogram',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
